#!/usr/bin/env python3
"""
Medical365 Local SEO Page Generator
Generates ~70 high-converting landing pages for Indian healthcare market.
"""

import os
import re

# ─── Load template ────────────────────────────────────────────────────────────
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "template.html")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "pages")
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
    TEMPLATE = f.read()

# ─── Postal codes ─────────────────────────────────────────────────────────────
POSTAL_CODES = {
    "Jaipur": "302001", "Jodhpur": "342001", "Udaipur": "313001",
    "Kota": "324001", "Ajmer": "305001", "Bikaner": "334001",
    "Bhilwara": "311001", "Alwar": "301001", "Sikar": "332001",
    "Pali": "306401", "Bharatpur": "321001", "Sri Ganganagar": "335001",
    "Mansarovar": "302020", "Vaishali Nagar": "302021", "Malviya Nagar": "302017",
    "C-Scheme": "302001", "Raja Park": "302004", "Jagatpura": "302017",
    "Tonk Road": "302015", "Bapu Nagar": "302015", "Jhotwara": "302012",
    "Vidyadhar Nagar": "302023",
}

# ─── Testimonials pool ────────────────────────────────────────────────────────
TESTIMONIALS = [
    {
        "quote": "Medical365 transformed our OPD management completely. Patient wait times dropped by 65% in the first month. The offline sync feature is a lifesaver during power cuts.",
        "name": "Dr. Rajesh Sharma", "role": "Medical Director", "initials": "RS"
    },
    {
        "quote": "The GST-compliant billing alone saved us 15 hours of admin work every week. Implementation was smooth and the support team is extremely responsive.",
        "name": "Dr. Priya Gupta", "role": "Hospital Administrator", "initials": "PG"
    },
    {
        "quote": "As a multi-specialty clinic, we needed something that could handle EMR, pharmacy, and lab together. Medical365 does it all — and the ABDM compliance gave us peace of mind.",
        "name": "Dr. Amit Verma", "role": "Chief of Operations", "initials": "AV"
    },
    {
        "quote": "Switching from paper records to Medical365's EMR took just one week. Our doctors love the speech-to-text and the patient app has greatly improved follow-up rates.",
        "name": "Dr. Sunita Agarwal", "role": "Senior Consultant", "initials": "SA"
    },
    {
        "quote": "Revenue leakage was our biggest problem. After Medical365's RCM module, we recovered 28% more revenue in Q1 itself. Highly recommend for any serious healthcare facility.",
        "name": "Mr. Vikram Joshi", "role": "CFO, Multi-Speciality Hospital", "initials": "VJ"
    },
]

# ─── Page data ────────────────────────────────────────────────────────────────
# Each dict: location, feature, keyword_category, slug_suffix
PAGES = [
    # ── Category 1: Hospital & Clinic Management ──────────────────────────────
    {
        "location": "Rajasthan", "feature": "Hospital Management Software",
        "slug": "best-hospital-management-software-rajasthan",
        "h1": "Best Hospital Management Software in Rajasthan — Trusted by 500+ Facilities",
        "meta_title": "Best Hospital Management Software in Rajasthan | Medical365",
        "meta_desc": "Looking for the best hospital management software in Rajasthan? Medical365 offers cloud-based HMS with ABDM compliance, EMR, billing & more. Book a free demo today.",
        "faq": [
            ("What makes Medical365 the best hospital management software in Rajasthan?",
             "Medical365 is purpose-built for Indian healthcare with full ABDM, DPDP Act 2023, and EHR compliance. It covers OPD, IPD, pharmacy, lab, billing, and telemedicine in one platform — with offline sync for low-connectivity areas common in Rajasthan."),
            ("How long does implementation take for a hospital in Rajasthan?",
             "Most hospitals go live within 5–7 working days. Our onboarding team handles data migration, staff training, and configuration remotely or on-site across Rajasthan at no extra cost."),
            ("Is Medical365 compatible with government health schemes like Ayushman Bharat?",
             "Yes. Medical365 supports Ayushman Bharat, ABHA ID integration, Pradhan Mantri Jan Arogya Yojana (PMJAY) claim workflows, and all state-level Rajasthan health scheme billing requirements."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Jaipur", "feature": "Clinic Management System",
        "slug": "clinic-management-system-jaipur",
        "h1": "Clinic Management System in Jaipur — Streamline Every Patient Visit",
        "meta_title": "Clinic Management System in Jaipur | Medical365 HMS",
        "meta_desc": "Medical365 offers a powerful clinic management system in Jaipur with OPD scheduling, digital records, GST billing, and ABDM compliance. Book a free demo.",
        "faq": [
            ("What does a clinic management system do for clinics in Jaipur?",
             "It automates patient registration, appointment scheduling, EMR documentation, billing, and pharmacy management — reducing manual workload by up to 70% for busy Jaipur clinics."),
            ("Can a small single-doctor clinic in Jaipur afford Medical365?",
             "Absolutely. Medical365 offers flexible plans starting from solo practitioners to large multi-specialty hospitals. Contact us for pricing tailored to your clinic size in Jaipur."),
            ("Does Medical365 support Hindi language for staff and patients in Jaipur?",
             "Yes, Medical365 supports multilingual interfaces including Hindi, making it easy for staff and patients across Jaipur to use the system comfortably."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Jodhpur", "feature": "Outpatient Software Solutions",
        "slug": "outpatient-software-solutions-jodhpur",
        "h1": "Outpatient Software Solutions in Jodhpur — Faster OPD, Happier Patients",
        "meta_title": "Outpatient Software Solutions in Jodhpur | Medical365 OPD",
        "meta_desc": "Best outpatient software solutions for hospitals and clinics in Jodhpur. Reduce OPD wait times by 60% with Medical365's smart queue, digital records, and billing.",
        "faq": [
            ("How does Medical365 reduce OPD wait times in Jodhpur hospitals?",
             "Medical365's smart token management, digital check-in kiosks, and real-time queue dashboards reduce average OPD wait times by 60% — keeping patients and staff in Jodhpur happy."),
            ("Can Medical365 handle multi-doctor OPD scheduling in Jodhpur?",
             "Yes, Medical365 supports unlimited doctors, departments, and consultation rooms with intelligent slot management and auto-scheduling for any size facility in Jodhpur."),
            ("Is online appointment booking available for patients in Jodhpur?",
             "Yes. Patients in Jodhpur can book appointments via your hospital's website, app, or WhatsApp integration — reducing front-desk load dramatically."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Udaipur", "feature": "Inpatient Management Software",
        "slug": "inpatient-management-software-udaipur",
        "h1": "Inpatient Management Software in Udaipur — Full IPD Control, Zero Gaps",
        "meta_title": "Inpatient Management Software in Udaipur | Medical365 IPD",
        "meta_desc": "Comprehensive inpatient management software for hospitals in Udaipur. Manage bed allocation, nursing notes, ward rounds, discharge summaries, and insurance billing.",
        "faq": [
            ("What IPD features does Medical365 offer for Udaipur hospitals?",
             "Medical365 covers full IPD workflows: admission, bed management, ward rounds, nursing notes, diet management, discharge planning, and NABH-compliant documentation — all in one system."),
            ("How does bed management work in Medical365 for Udaipur hospitals?",
             "A real-time colour-coded bed dashboard shows availability, cleaning status, and patient allocation across all wards. Staff in Udaipur can manage beds from any device."),
            ("Does Medical365 support TPA and insurance billing for IPD in Udaipur?",
             "Yes. Medical365 integrates with all major TPAs and insurance providers operating in Rajasthan, with automated pre-authorization, claim submission, and reconciliation."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Mansarovar", "feature": "Telemedicine Platform",
        "slug": "telemedicine-platform-clinics-mansarovar",
        "h1": "Telemedicine Platform for Clinics in Mansarovar, Jaipur — Consult from Anywhere",
        "meta_title": "Telemedicine Platform for Clinics in Mansarovar | Medical365",
        "meta_desc": "Launch telemedicine for your clinic in Mansarovar, Jaipur. HD video consults, e-prescriptions, digital follow-ups & ABDM-compliant records with Medical365.",
        "faq": [
            ("How quickly can a clinic in Mansarovar launch telemedicine with Medical365?",
             "Your telemedicine clinic in Mansarovar can be live within 48 hours. Medical365 provides branded video call links, e-prescription pads, and payment collection out of the box."),
            ("Is telemedicine legal and compliant for doctors in Mansarovar Jaipur?",
             "Yes. Medical365 is fully compliant with the Telemedicine Practice Guidelines 2020 issued by the Indian Medical Council, and all records are ABDM and DPDP Act ready."),
            ("Can patients in Mansarovar pay online for telemedicine consultations?",
             "Yes. Patients can pay via UPI, credit/debit card, or net banking. Medical365 integrates with leading Indian payment gateways for seamless collection."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Vaishali Nagar", "feature": "Hospital Queue & Token Management",
        "slug": "hospital-queue-token-management-vaishali-nagar",
        "h1": "Hospital Queue & Token Management in Vaishali Nagar — End the Chaos",
        "meta_title": "Hospital Queue & Token Management in Vaishali Nagar | Medical365",
        "meta_desc": "Smart queue and token management for hospitals in Vaishali Nagar, Jaipur. Digital tokens, SMS alerts, real-time boards & OPD flow automation with Medical365.",
        "faq": [
            ("How does Medical365 queue management work for hospitals in Vaishali Nagar?",
             "Patients receive digital tokens via SMS or app. Real-time display boards show queue status. Doctors control their pace digitally, and average wait times drop by up to 65% in Vaishali Nagar facilities."),
            ("Can patients book tokens online before arriving at the clinic?",
             "Yes. Online token booking lets patients in Vaishali Nagar and nearby areas reserve their slot from home, reducing crowding at reception."),
            ("Does the token management system work without internet?",
             "Yes. Medical365's offline-first architecture keeps queue management running even during internet outages, with automatic sync when connectivity is restored."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Kota", "feature": "Healthcare Kiosk",
        "slug": "healthcare-kiosk-providers-kota",
        "h1": "Healthcare Kiosk Providers in Kota — Self-Service That Speeds Up Your OPD",
        "meta_title": "Healthcare Kiosk Providers in Kota | Medical365 Patient Kiosk",
        "meta_desc": "Medical365 healthcare kiosks for hospitals in Kota. Patient self-check-in, token printing, appointment confirmation & vitals capture. Cut reception workload by 50%.",
        "faq": [
            ("What can patients do at a Medical365 healthcare kiosk in Kota?",
             "Patients can self-register, check in, print tokens, confirm appointments, pay bills, and collect lab reports — all without waiting at the reception desk in Kota hospitals."),
            ("What hardware is required for Medical365 kiosks in Kota?",
             "Medical365 works with standard touch-screen kiosk hardware available in Kota. We help source, configure, and install the kiosk as part of our onboarding service."),
            ("Are kiosks accessible for elderly patients who may not be tech-savvy?",
             "Yes. Our kiosk UI features large fonts, simple Hindi/English language options, and a one-touch help button that alerts reception staff for assistance."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Ajmer", "feature": "Virtual OPD Software",
        "slug": "virtual-opd-software-ajmer",
        "h1": "Virtual OPD Software in Ajmer — Run Your Outpatient Clinic Online",
        "meta_title": "Virtual OPD Software in Ajmer | Medical365 Telemedicine OPD",
        "meta_desc": "Run a complete virtual OPD in Ajmer with Medical365. Online scheduling, video consultations, digital prescriptions, and automated follow-ups — all ABDM compliant.",
        "faq": [
            ("What is virtual OPD and how does it benefit clinics in Ajmer?",
             "Virtual OPD lets your Ajmer clinic run online consultations via video, reducing patient travel, eliminating physical queues, and expanding your reach to patients in surrounding districts."),
            ("How are prescriptions handled in a virtual OPD in Ajmer?",
             "Doctors generate digitally signed e-prescriptions that patients receive instantly via SMS and WhatsApp — legally valid and ABDM-compliant for all Ajmer practices."),
            ("Can virtual OPD in Ajmer integrate with my existing in-person clinic system?",
             "Yes. Medical365 unifies your in-person and virtual OPD in a single dashboard, with shared patient records, appointments, and billing."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Bhilwara", "feature": "Medical Camp Management Software",
        "slug": "medical-camp-management-software-bhilwara",
        "h1": "Medical Camp Management Software in Bhilwara — Organise, Track & Report",
        "meta_title": "Medical Camp Management Software in Bhilwara | Medical365",
        "meta_desc": "Manage medical camps in Bhilwara efficiently with Medical365. Patient registration, vitals tracking, bulk reporting, and ABHA ID integration — all paperless.",
        "faq": [
            ("How does Medical365 help manage medical camps in Bhilwara?",
             "Medical365's camp module handles bulk patient registration, vitals capture, doctor consultations, medicine dispensing, and real-time reporting — all without paper, even in offline areas of Bhilwara."),
            ("Can Medical365 generate government health camp reports for Bhilwara?",
             "Yes. The system generates NHM, RBSK, and other government-mandated camp reports instantly, saving hours of manual compilation for Bhilwara health teams."),
            ("Is ABHA ID creation supported during medical camps in Bhilwara?",
             "Yes. Medical365 integrates with the ABDM gateway for ABHA ID creation and health record linking at the point of camp registration."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Malviya Nagar", "feature": "Doctor Mobile App",
        "slug": "doctor-mobile-app-malviya-nagar",
        "h1": "Doctor Mobile App in Malviya Nagar, Jaipur — Practice From Your Phone",
        "meta_title": "Doctor Mobile App in Malviya Nagar Jaipur | Medical365",
        "meta_desc": "Medical365's doctor mobile app for Malviya Nagar, Jaipur. View patient records, write prescriptions, manage appointments & get clinic reports on Android & iOS.",
        "faq": [
            ("What can doctors in Malviya Nagar do with the Medical365 mobile app?",
             "Doctors can view patient history, write e-prescriptions, review lab reports, manage appointments, conduct telemedicine consultations, and monitor clinic analytics — all from their smartphone."),
            ("Is the Medical365 doctor app available on Android and iOS in India?",
             "Yes. The Medical365 doctor app is available on both Google Play Store and Apple App Store, free for all Medical365 subscribers."),
            ("Is patient data secure on the Medical365 doctor mobile app?",
             "Yes. All data is encrypted end-to-end, stored on Indian cloud servers, and fully compliant with the DPDP Act 2023 — your patients' data in Malviya Nagar is always protected."),
        ],
        "testimonial_idx": 4,
    },
    # ── Category 2: Clinical & Medical Operations ─────────────────────────────
    {
        "location": "Bikaner", "feature": "EMR Software",
        "slug": "emr-software-hospitals-bikaner",
        "h1": "EMR Software for Hospitals in Bikaner — Digital Records, Better Care",
        "meta_title": "EMR Software for Hospitals in Bikaner | Medical365 Electronic Medical Records",
        "meta_desc": "Best EMR software for hospitals in Bikaner. Medical365 offers SOAP-format digital records, speech-to-text, EHR Standards of India compliance, and offline sync.",
        "faq": [
            ("What EMR features does Medical365 offer for hospitals in Bikaner?",
             "Medical365 EMR includes SOAP and custom templates, speech-to-text dictation, patient history timelines, diagnostic integration, and EHR Standards of India compliance — tailored for Bikaner hospital workflows."),
            ("Can Medical365 EMR work in areas of Bikaner with poor internet connectivity?",
             "Yes. Medical365 is built offline-first, meaning doctors in remote parts of Bikaner can continue documenting records without internet, with automatic sync when connectivity is available."),
            ("How is patient data migrated from paper records to Medical365 EMR in Bikaner?",
             "Our team provides on-site data entry support and scanning services to digitise existing records. Most Bikaner hospitals complete migration within 2 weeks."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "C-Scheme", "feature": "Clinical Assessment Form Software",
        "slug": "clinical-assessment-form-software-c-scheme",
        "h1": "Clinical Assessment Form Software in C-Scheme, Jaipur — Standardise & Speed Up",
        "meta_title": "Clinical Assessment Form Software in C-Scheme Jaipur | Medical365",
        "meta_desc": "Customisable clinical assessment forms for hospitals in C-Scheme, Jaipur. Build SOAP, triage, specialty-specific forms with Medical365's no-code form builder.",
        "faq": [
            ("Can clinics in C-Scheme Jaipur create custom clinical assessment forms?",
             "Yes. Medical365's drag-and-drop form builder lets any clinic in C-Scheme create department-specific assessment forms — cardiology, orthopaedics, paediatrics, and more — without any coding."),
            ("Are clinical assessment forms linked to patient EMR in Medical365?",
             "Absolutely. Every completed form is automatically saved to the patient's EMR, creating a complete longitudinal health record accessible by any authorised doctor."),
            ("Can clinical forms be filled on tablets during ward rounds in C-Scheme hospitals?",
             "Yes. Medical365 is fully responsive and works on tablets, making bedside form filling fast and easy for doctors and nurses in C-Scheme and across Jaipur."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Alwar", "feature": "Operation Theater Management System",
        "slug": "operation-theater-management-alwar",
        "h1": "Operation Theater Management System in Alwar — Schedule, Track & Comply",
        "meta_title": "Operation Theater Management System in Alwar | Medical365 OT",
        "meta_desc": "Comprehensive OT management system for hospitals in Alwar. Schedule surgeries, manage OT teams, track consumables, and maintain NABH-compliant records with Medical365.",
        "faq": [
            ("What OT management features does Medical365 offer for Alwar hospitals?",
             "Medical365 OT module covers surgical scheduling, team assignments, anaesthesia records, consumable tracking, post-op notes, and NABH-compliant OT register maintenance for Alwar hospitals."),
            ("How does Medical365 prevent OT scheduling conflicts in Alwar hospitals?",
             "The smart OT scheduler shows real-time availability of theatres, surgeons, anaesthetists, and equipment — preventing double-booking and maximising Alwar hospital OT utilisation."),
            ("Can OT consumable inventory be tracked automatically in Medical365?",
             "Yes. Medical365 deducts consumables from inventory automatically at the time of surgery, triggering reorder alerts when stock falls below the defined threshold."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Sikar", "feature": "Nursing Management System",
        "slug": "nursing-management-system-sikar",
        "h1": "Nursing Management System in Sikar — Empower Your Nursing Teams",
        "meta_title": "Nursing Management System in Sikar | Medical365 Nursing Module",
        "meta_desc": "Digital nursing management for hospitals in Sikar. Nurse scheduling, care plans, medication administration records (MAR), and shift handover notes with Medical365.",
        "faq": [
            ("What does Medical365's nursing module offer hospitals in Sikar?",
             "It covers nurse duty scheduling, patient care plans, medication administration records (MAR), vital sign charting, incident reporting, and digital shift handover for Sikar hospitals."),
            ("How does Medical365 improve medication safety for nurses in Sikar?",
             "The MAR module shows doctor-prescribed medications with dosage and timing. Nurses in Sikar can mark administration, add notes, and flag missed doses — reducing medication errors significantly."),
            ("Can head nurses in Sikar manage duty rosters on Medical365?",
             "Yes. Head nurses can create, edit, and publish duty rosters with leave management, shift swaps, and load balancing across departments."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Jaipur", "feature": "LIMS Laboratory Information Management System",
        "slug": "lims-laboratory-information-management-jaipur",
        "h1": "LIMS — Laboratory Information Management System in Jaipur",
        "meta_title": "LIMS Laboratory Information Management System in Jaipur | Medical365",
        "meta_desc": "Best LIMS for diagnostic labs and hospitals in Jaipur. Automate lab orders, result entry, auto-reporting, TAT tracking, and NABL compliance with Medical365.",
        "faq": [
            ("What is LIMS and why do labs in Jaipur need it?",
             "LIMS (Laboratory Information Management System) automates the entire lab workflow from order receipt to result delivery — eliminating manual errors, reducing turnaround time, and ensuring traceability for Jaipur labs."),
            ("Does Medical365 LIMS support NABL accreditation requirements?",
             "Yes. Medical365 LIMS provides audit trails, quality control charting, inter-lab comparisons, and documentation templates aligned with NABL requirements for Indian labs."),
            ("Can Medical365 LIMS send lab reports automatically to patients in Jaipur?",
             "Yes. Patients receive digitally signed lab reports via SMS and WhatsApp as soon as results are validated — reducing front-desk queries and improving the Jaipur patient experience."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Jodhpur", "feature": "RIS & PACS Software",
        "slug": "ris-pacs-software-providers-jodhpur",
        "h1": "RIS & PACS Software Providers in Jodhpur — Radiology, Reimagined",
        "meta_title": "RIS & PACS Software in Jodhpur | Medical365 Radiology",
        "meta_desc": "Leading RIS and PACS software for radiology centres in Jodhpur. DICOM viewer, radiologist reporting, EMR integration, and cloud PACS storage with Medical365.",
        "faq": [
            ("What RIS features does Medical365 offer for radiology centres in Jodhpur?",
             "Medical365 RIS manages radiology order entry, technician workflow, radiologist reporting, turnaround time tracking, and integration with EMR for complete Jodhpur radiology department automation."),
            ("Does Medical365 include a DICOM viewer for radiologists in Jodhpur?",
             "Yes. Medical365 includes a web-based DICOM viewer for viewing X-rays, CT, MRI, and ultrasound images directly in the browser — no additional software needed for Jodhpur radiologists."),
            ("Can PACS images be stored securely in the cloud for Jodhpur hospitals?",
             "Yes. Medical365 offers cloud PACS storage on Indian servers with AES-256 encryption, role-based access, and anytime retrieval for authorised clinicians."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Raja Park", "feature": "Pharmacy Management Software",
        "slug": "pharmacy-management-software-raja-park",
        "h1": "Pharmacy Management Software in Raja Park, Jaipur — Zero Stockouts, Zero Errors",
        "meta_title": "Pharmacy Management Software in Raja Park Jaipur | Medical365",
        "meta_desc": "Best pharmacy management software for hospitals and standalone pharmacies in Raja Park, Jaipur. Inventory, expiry alerts, auto-reorder, billing, and EMR integration.",
        "faq": [
            ("What pharmacy management features does Medical365 offer in Raja Park?",
             "Medical365 covers drug inventory management, expiry date alerts, batch tracking, auto-reorder, GST-compliant billing, narcotic register maintenance, and direct integration with doctor EMR in Raja Park pharmacies."),
            ("How does Medical365 prevent expired medicines from being dispensed?",
             "The system flags medicines nearing expiry and prevents dispensing of expired stock, with automated alerts sent to the pharmacy manager well in advance."),
            ("Can Medical365 pharmacy module handle retail and in-patient dispensing?",
             "Yes. Medical365 supports both retail pharmacy sales and IPD patient charge dispensing from the same interface, with separate billing and inventory tracking."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Udaipur", "feature": "Blood Bank Software",
        "slug": "blood-bank-software-udaipur",
        "h1": "Blood Bank Software in Udaipur — Precision, Safety & Compliance",
        "meta_title": "Blood Bank Software in Udaipur | Medical365 Blood Bank Management",
        "meta_desc": "Comprehensive blood bank management software for hospitals in Udaipur. Donor management, cross-matching, inventory, expiry tracking, and SBTC compliance with Medical365.",
        "faq": [
            ("What does Medical365 blood bank software cover for Udaipur hospitals?",
             "Medical365 manages blood donor registration, blood group testing, cross-matching, component preparation, stock management, expiry alerts, and SBTC (State Blood Transfusion Council) compliance reporting for Udaipur hospitals."),
            ("How does Medical365 track blood unit expiry in Udaipur blood banks?",
             "Every unit is tracked with batch number, collection date, and expiry date. Automatic alerts are sent 3–7 days before expiry, and expired units are auto-quarantined from dispensable stock."),
            ("Can Medical365 blood bank software integrate with other hospital modules in Udaipur?",
             "Yes. Blood requests from OT, ICU, and ward nursing stations link directly to the blood bank — no phone calls or paper forms needed."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Jagatpura", "feature": "Speech to Text Medical Dictation",
        "slug": "speech-to-text-medical-dictation-jagatpura",
        "h1": "Speech to Text Medical Dictation Software in Jagatpura, Jaipur",
        "meta_title": "Speech to Text Medical Dictation in Jagatpura Jaipur | Medical365",
        "meta_desc": "Medical-grade speech-to-text dictation for doctors in Jagatpura, Jaipur. Dictate EMR notes, prescriptions, and discharge summaries in English or Hindi with Medical365.",
        "faq": [
            ("How does Medical365's speech-to-text dictation work for doctors in Jagatpura?",
             "Doctors in Jagatpura click the microphone icon in any EMR field and dictate — the system transcribes with over 95% accuracy for medical terminology in English and Hindi, saving 70% documentation time."),
            ("Does Medical365 speech-to-text support Hindi dictation for Indian doctors?",
             "Yes. Medical365 supports English and Hinglish (Hindi spoken with English medical terms) dictation, making it easy for doctors across Jagatpura and Jaipur to document naturally."),
            ("Is the dictated content secure and compliant with DPDP Act 2023?",
             "Yes. All dictated notes are processed on compliant Indian cloud infrastructure and stored with AES-256 encryption, fully meeting DPDP Act 2023 requirements."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Kota", "feature": "Diabetes Care Management Software",
        "slug": "diabetes-care-management-software-kota",
        "h1": "Diabetes Care Management Software in Kota — Track, Monitor & Intervene Early",
        "meta_title": "Diabetes Care Management Software in Kota | Medical365",
        "meta_desc": "Specialised diabetes care management for clinics and hospitals in Kota. HbA1c tracking, diet plans, medication adherence, and patient education with Medical365.",
        "faq": [
            ("How does Medical365 help diabetes clinics in Kota manage patients?",
             "Medical365's chronic care module tracks HbA1c, blood glucose trends, medications, dietary adherence, and foot care — with automated alerts for out-of-range values for diabetes patients in Kota."),
            ("Can patients in Kota track their own diabetes readings on the Medical365 app?",
             "Yes. Patients can log daily blood glucose, weight, and diet in the Medical365 patient app, with readings visible to their doctor in real time."),
            ("Does Medical365 generate diabetes care reports for Kota clinics?",
             "Yes. Comprehensive HbA1c trend reports, medication adherence scores, and population health dashboards help Kota diabetes clinics identify high-risk patients early."),
        ],
        "testimonial_idx": 4,
    },
    # ── Category 3: Financial & Revenue Management ────────────────────────────
    {
        "location": "Rajasthan", "feature": "Hospital Revenue Cycle Management",
        "slug": "hospital-revenue-cycle-management-rajasthan",
        "h1": "Hospital Revenue Cycle Management in Rajasthan — Stop Revenue Leakage Today",
        "meta_title": "Hospital Revenue Cycle Management in Rajasthan | Medical365 RCM",
        "meta_desc": "Best hospital RCM software in Rajasthan. Automated billing, TPA claims, GST invoicing, and revenue analytics. Recover up to 35% more revenue with Medical365.",
        "faq": [
            ("What is Revenue Cycle Management (RCM) and why do Rajasthan hospitals need it?",
             "RCM is the end-to-end process of managing healthcare billing from patient registration to final payment. Medical365 RCM automates this, reducing claim rejections and recovering 25–35% more revenue for Rajasthan hospitals."),
            ("How does Medical365 handle TPA and insurance billing in Rajasthan?",
             "Medical365 integrates with all major TPAs and insurance companies operating in Rajasthan, with pre-authorization workflows, claim submission, and real-time reconciliation dashboards."),
            ("Does Medical365 RCM support GST invoicing for hospitals in Rajasthan?",
             "Yes. Medical365 generates GST-compliant invoices with proper GSTIN, HSN/SAC codes, and e-invoicing integration — fully meeting Rajasthan GST requirements."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Ajmer", "feature": "Healthcare Billing Software",
        "slug": "healthcare-billing-software-ajmer",
        "h1": "Healthcare Billing Software in Ajmer — Fast, Accurate & GST-Compliant",
        "meta_title": "Healthcare Billing Software in Ajmer | Medical365 Hospital Billing",
        "meta_desc": "GST-compliant healthcare billing software for hospitals and clinics in Ajmer. Automate OPD/IPD billing, insurance claims, and financial reporting with Medical365.",
        "faq": [
            ("How does Medical365 billing software simplify GST for clinics in Ajmer?",
             "Medical365 auto-applies correct GST rates to each service, generates e-invoices, and creates monthly GSTR reports ready for filing — eliminating billing errors for Ajmer clinics."),
            ("Can Medical365 billing work across multiple departments in Ajmer hospitals?",
             "Yes. Billing is integrated across OPD, IPD, pharmacy, lab, radiology, and canteen — all consolidated into a single patient bill, reducing disputes at discharge."),
            ("How quickly can billing staff in Ajmer learn Medical365?",
             "Most billing staff are proficient within 1–2 days. Medical365 provides dedicated training videos, user manuals in Hindi, and live support for Ajmer onboarding."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Tonk Road", "feature": "Accounts Payable Software",
        "slug": "accounts-payable-software-hospitals-tonk-road",
        "h1": "Accounts Payable Software for Hospitals in Tonk Road, Jaipur",
        "meta_title": "Accounts Payable Software for Hospitals in Tonk Road Jaipur | Medical365",
        "meta_desc": "Automate hospital accounts payable in Tonk Road, Jaipur. Vendor management, purchase orders, invoice matching, and payment workflows with Medical365.",
        "faq": [
            ("How does Medical365 automate accounts payable for hospitals in Tonk Road?",
             "Medical365 manages vendor onboarding, purchase orders, goods receipt notes, invoice matching, approval workflows, and payment scheduling — eliminating manual AP processes for Tonk Road hospitals."),
            ("Can Medical365 handle multiple vendors and contracts for a Tonk Road hospital?",
             "Yes. Medical365 maintains a vendor master with contract terms, rate cards, and payment schedules. Automated PO generation and three-way matching prevents overpayments."),
            ("Does Medical365 AP module integrate with the hospital general ledger?",
             "Yes. All AP transactions post automatically to the general ledger with proper cost centre allocation, giving finance teams in Tonk Road real-time P&L visibility."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Bikaner", "feature": "Hospital Ledger and Accounting Software",
        "slug": "hospital-ledger-accounting-software-bikaner",
        "h1": "Hospital Ledger & Accounting Software in Bikaner — Financial Clarity, Zero Errors",
        "meta_title": "Hospital Ledger & Accounting Software in Bikaner | Medical365",
        "meta_desc": "Complete hospital accounting and ledger management for facilities in Bikaner. Chart of accounts, multi-department P&L, GST returns, and audit trails with Medical365.",
        "faq": [
            ("What accounting features does Medical365 offer for hospitals in Bikaner?",
             "Medical365 provides a full double-entry accounting system with chart of accounts, cost centres, budget vs. actuals, multi-department P&L, GST returns, and statutory audit reports for Bikaner hospitals."),
            ("Can Medical365 integrate with Tally for hospitals in Bikaner?",
             "Yes. Medical365 offers Tally export compatibility, allowing Bikaner hospitals to sync financial transactions with their existing Tally ERP setup seamlessly."),
            ("How does Medical365 help with year-end audit for Bikaner hospitals?",
             "Medical365 generates audit-ready trial balances, income statements, and transaction logs with full traceability — making CA audits faster and less stressful."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Jaipur", "feature": "Medical Payment Gateway Integration",
        "slug": "medical-payment-gateway-integration-jaipur",
        "h1": "Medical Payment Gateway Integration in Jaipur — UPI, Cards & EMI for Healthcare",
        "meta_title": "Medical Payment Gateway Integration in Jaipur | Medical365",
        "meta_desc": "Accept UPI, credit card, net banking, and EMI payments for your hospital or clinic in Jaipur. Medical365 integrates with leading Indian payment gateways.",
        "faq": [
            ("Which payment methods can Jaipur hospitals accept through Medical365?",
             "Medical365 supports UPI (PhonePe, GPay, Paytm), credit/debit cards, net banking, wallets, and healthcare EMI options — covering 100% of your patients' preferred payment methods in Jaipur."),
            ("Is the Medical365 payment gateway secure for patients in Jaipur?",
             "Yes. All transactions use PCI-DSS compliant payment infrastructure with 256-bit SSL encryption. Patient payment data is never stored on Medical365 servers."),
            ("Can patients in Jaipur pay in advance for appointments online?",
             "Yes. Medical365 supports online advance payment collection during appointment booking — reducing no-shows by up to 40% for Jaipur clinics."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Jhotwara", "feature": "Hospital Financial Reporting Dashboard",
        "slug": "hospital-financial-reporting-dashboard-jhotwara",
        "h1": "Hospital Financial Reporting Dashboard in Jhotwara, Jaipur — Insights at a Glance",
        "meta_title": "Hospital Financial Reporting Dashboard in Jhotwara Jaipur | Medical365",
        "meta_desc": "Real-time financial dashboards for hospitals in Jhotwara, Jaipur. Revenue, expenses, department-wise P&L, and KPI tracking for healthcare CFOs with Medical365.",
        "faq": [
            ("What financial KPIs can Jhotwara hospital CFOs track in Medical365?",
             "Medical365's dashboard tracks daily revenue, collection efficiency, department-wise profitability, outstanding receivables, expense ratios, bed occupancy value, and GST liability — all in real time."),
            ("Can Medical365 financial reports be exported for board meetings?",
             "Yes. All reports export to PDF and Excel in one click, with custom date ranges and department filters — ready for board presentations for Jhotwara hospital leadership."),
            ("How often is financial data updated in Medical365's dashboard?",
             "Financial data updates in real time as transactions occur. No waiting for end-of-day reports — Jhotwara hospital CFOs see live numbers 24/7."),
        ],
        "testimonial_idx": 0,
    },
    # ── Category 4: Patient Experience ───────────────────────────────────────
    {
        "location": "Udaipur", "feature": "Hospital Online Scheduling Software",
        "slug": "hospital-online-scheduling-software-udaipur",
        "h1": "Hospital Online Scheduling Software in Udaipur — Book Anytime, From Anywhere",
        "meta_title": "Hospital Online Scheduling Software in Udaipur | Medical365",
        "meta_desc": "Online appointment scheduling for hospitals in Udaipur. Let patients book 24/7 via web, app or WhatsApp. Reduce no-shows and front-desk calls with Medical365.",
        "faq": [
            ("How do patients in Udaipur book appointments online with Medical365?",
             "Patients visit your hospital's website or WhatsApp link, select their department and doctor, choose a slot, and pay a booking fee if required — all in under 2 minutes, 24/7."),
            ("How does Medical365 reduce appointment no-shows for Udaipur hospitals?",
             "Automated SMS and WhatsApp reminders are sent 24 hours and 1 hour before appointments, with a one-tap rescheduling option — cutting Udaipur no-show rates by up to 45%."),
            ("Can Udaipur hospitals offer family appointment booking through Medical365?",
             "Yes. Patients can book appointments for family members under one account, with separate medical records maintained for each person."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Vidyadhar Nagar", "feature": "Patient Portal Software",
        "slug": "patient-portal-software-vidyadhar-nagar",
        "h1": "Patient Portal Software in Vidyadhar Nagar, Jaipur — Put Patients in Control",
        "meta_title": "Patient Portal Software in Vidyadhar Nagar Jaipur | Medical365",
        "meta_desc": "Empower patients in Vidyadhar Nagar with Medical365's patient portal. Access records, reports, prescriptions, appointments, and billing — all in one secure place.",
        "faq": [
            ("What can patients in Vidyadhar Nagar do through the Medical365 patient portal?",
             "Patients can view medical records, download lab reports, access prescriptions, book appointments, pay bills, send messages to their doctor, and track their health history — all through a secure portal."),
            ("Is the Medical365 patient portal available in Hindi for Vidyadhar Nagar patients?",
             "Yes. The patient portal and mobile app are available in both English and Hindi, making it accessible to all patients regardless of language preference."),
            ("How secure is the patient portal for Vidyadhar Nagar residents?",
             "The portal uses OTP-based login, session timeouts, and AES-256 encryption — meeting DPDP Act 2023 standards to protect every patient's health data."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Rajasthan", "feature": "Patient Mobile App",
        "slug": "patient-mobile-app-developers-rajasthan",
        "h1": "Patient Mobile App for Hospitals in Rajasthan — Engage Every Patient, Every Day",
        "meta_title": "Patient Mobile App Developers in Rajasthan | Medical365",
        "meta_desc": "Branded patient mobile app for hospitals across Rajasthan. Appointments, reports, prescriptions, bill payments, and telemedicine — all in your hospital's branded app.",
        "faq": [
            ("Can hospitals in Rajasthan have a branded patient app with Medical365?",
             "Yes. Medical365 provides a white-label patient app branded with your hospital's name and logo, available on Android and iOS — giving Rajasthan hospitals a professional digital presence."),
            ("What patient engagement features does the Medical365 app offer?",
             "The app covers appointment booking, teleconsultation, report access, medication reminders, health tips, feedback surveys, and loyalty points — keeping patients engaged between visits."),
            ("How long does it take to launch a patient app for a hospital in Rajasthan?",
             "Your branded patient app is ready within 7–10 business days. Medical365 handles app store submission, testing, and launch support across Rajasthan."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Jodhpur", "feature": "Hospital Communication Management",
        "slug": "hospital-communication-management-jodhpur",
        "h1": "Hospital Communication Management in Jodhpur — Right Message, Right Patient, Right Time",
        "meta_title": "Hospital Communication Management in Jodhpur | Medical365",
        "meta_desc": "Automate patient communication for hospitals in Jodhpur. SMS, WhatsApp, email reminders, discharge instructions, and health education with Medical365.",
        "faq": [
            ("What patient communication automations does Medical365 offer for Jodhpur hospitals?",
             "Medical365 automates appointment reminders, lab report notifications, discharge instructions, medication reminders, follow-up calls, and health education messages via SMS and WhatsApp for Jodhpur patients."),
            ("Can Jodhpur hospitals send bulk health camp announcements through Medical365?",
             "Yes. Medical365's bulk communication module lets hospitals send targeted SMS/WhatsApp messages to patient segments by age, condition, or last visit date."),
            ("Does Medical365 communication integrate with WhatsApp Business in Jodhpur?",
             "Yes. Medical365 integrates with WhatsApp Business API for two-way patient communication — patients can even confirm appointments and request reports via WhatsApp."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Alwar", "feature": "Healthcare Feedback and Satisfaction Surveys",
        "slug": "healthcare-feedback-satisfaction-surveys-alwar",
        "h1": "Healthcare Feedback & Satisfaction Surveys in Alwar — Listen, Improve, Grow",
        "meta_title": "Healthcare Feedback & Satisfaction Surveys in Alwar | Medical365",
        "meta_desc": "Automated patient feedback and satisfaction survey tools for hospitals in Alwar. Collect NPS, CSAT scores, and actionable insights with Medical365.",
        "faq": [
            ("How does Medical365 collect patient feedback for hospitals in Alwar?",
             "Medical365 automatically sends post-visit surveys via SMS or WhatsApp after each appointment, capturing satisfaction scores, free-text feedback, and NPS ratings for Alwar hospitals."),
            ("Can Alwar hospital management see real-time feedback dashboards?",
             "Yes. Management sees live satisfaction scores, negative feedback alerts, department-wise ratings, and trend charts — enabling instant service recovery for Alwar hospitals."),
            ("How does patient feedback help improve services in Alwar hospitals?",
             "Medical365 segments feedback by doctor, department, and service type — identifying specific pain points so Alwar hospital teams can make targeted improvements."),
        ],
        "testimonial_idx": 0,
    },
    # ── Category 5: Hospital IT & Infrastructure ──────────────────────────────
    {
        "location": "Jaipur", "feature": "Healthcare Cloud Migration Services",
        "slug": "healthcare-cloud-migration-services-jaipur",
        "h1": "Healthcare Cloud Migration Services in Jaipur — Move Safely, Scale Freely",
        "meta_title": "Healthcare Cloud Migration Services in Jaipur | Medical365",
        "meta_desc": "Expert healthcare cloud migration for hospitals in Jaipur. Move from on-premise to cloud securely with zero downtime, full data integrity, and ABDM compliance.",
        "faq": [
            ("How does Medical365 ensure zero data loss during cloud migration for Jaipur hospitals?",
             "Medical365 uses phased migration with parallel running, data validation checkpoints, and rollback capability — ensuring not a single patient record is lost during cloud migration for Jaipur hospitals."),
            ("Will cloud migration disrupt hospital operations in Jaipur?",
             "No. Medical365 performs migrations during off-peak hours with a tested rollback plan. Most Jaipur hospitals experience zero downtime during the cutover phase."),
            ("What cloud infrastructure does Medical365 use for Jaipur healthcare data?",
             "Medical365 uses AWS and Azure data centres located in India (Mumbai region), ensuring patient data stays within Indian borders and meets all DPDP Act 2023 data residency requirements."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Kota", "feature": "Hospital Data Backup and Recovery",
        "slug": "hospital-data-backup-recovery-kota",
        "h1": "Hospital Data Backup & Recovery in Kota — Your Data, Always Safe",
        "meta_title": "Hospital Data Backup & Recovery in Kota | Medical365",
        "meta_desc": "Enterprise-grade data backup and disaster recovery for hospitals in Kota. Automated backups, point-in-time recovery, and 99.99% data durability with Medical365.",
        "faq": [
            ("How frequently does Medical365 back up hospital data for Kota facilities?",
             "Medical365 performs incremental backups every 15 minutes and full backups daily. Data is stored in geographically redundant Indian data centres with 99.99% durability for Kota hospitals."),
            ("How quickly can Kota hospitals restore data after a system failure?",
             "Medical365's recovery time objective (RTO) is under 4 hours for complete restoration, with point-in-time recovery to any 15-minute window in the past 30 days."),
            ("Is hospital data backed up by Medical365 encrypted in Kota?",
             "Yes. All backup data is encrypted using AES-256 both in transit and at rest, stored on Indian cloud servers with strict access controls — fully DPDP Act 2023 compliant."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Rajasthan", "feature": "FHIR HL7 Compliant Software",
        "slug": "fhir-hl7-compliant-software-rajasthan",
        "h1": "FHIR HL7 Compliant Healthcare Software in Rajasthan — Future-Ready Interoperability",
        "meta_title": "FHIR HL7 Compliant Software in Rajasthan | Medical365",
        "meta_desc": "FHIR R4 and HL7 compliant hospital management software for Rajasthan. Enable seamless health data exchange, ABDM integration, and national health stack compatibility.",
        "faq": [
            ("Why is FHIR HL7 compliance important for hospitals in Rajasthan?",
             "FHIR R4 and HL7 standards enable Rajasthan hospitals to share health data securely with other systems — including ABDM, insurance companies, and referring hospitals — ensuring interoperability and regulatory compliance."),
            ("Is Medical365 certified as FHIR and HL7 compliant for Indian healthcare?",
             "Yes. Medical365 is built on FHIR R4 and HL7 v2.x standards and is fully integrated with the Ayushman Bharat Digital Mission (ABDM) health information exchange."),
            ("How does FHIR compliance benefit patients in Rajasthan hospitals?",
             "Patients can share their medical history with any ABDM-connected healthcare provider, eliminating repetitive tests and enabling continuity of care across Rajasthan."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Bhilwara", "feature": "On-Premise Hospital Software",
        "slug": "on-prem-hospital-software-bhilwara",
        "h1": "On-Premise Hospital Management Software in Bhilwara — Your Data, Your Servers",
        "meta_title": "On-Premise Hospital Software in Bhilwara | Medical365 On-Prem HMS",
        "meta_desc": "Medical365 on-premise hospital software for facilities in Bhilwara preferring local data control. Full HMS features on your own servers with cloud backup options.",
        "faq": [
            ("Does Medical365 offer on-premise deployment for hospitals in Bhilwara?",
             "Yes. Medical365 is available as a fully on-premise deployment for Bhilwara hospitals that prefer to host data locally, with optional cloud backup for disaster recovery."),
            ("What server specifications are needed for Medical365 on-premise in Bhilwara?",
             "Medical365 on-premise runs on standard Linux or Windows Server hardware. Our team assesses your Bhilwara facility's size and recommends appropriate server specifications during pre-sales consultation."),
            ("Can Medical365 on-premise in Bhilwara be connected to the ABDM network?",
             "Yes. Even on-premise deployments can connect to the ABDM health information exchange through our secure API gateway, maintaining full national health stack compliance."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Ajmer", "feature": "Multilingual HIMS",
        "slug": "multilingual-hims-ajmer",
        "h1": "Multilingual Hospital Information Management System in Ajmer",
        "meta_title": "Multilingual HIMS in Ajmer | Medical365 Hospital Information System",
        "meta_desc": "Medical365 multilingual HIMS for hospitals in Ajmer. Run your entire hospital in Hindi, English, or both. Patient records, billing, and reports in your preferred language.",
        "faq": [
            ("Which languages does Medical365 HIMS support for hospitals in Ajmer?",
             "Medical365 supports English and Hindi interfaces for all staff-facing modules, with patient-facing materials also available in Hindi — making the system accessible for every staff member in Ajmer."),
            ("Can different departments in an Ajmer hospital use different language settings?",
             "Yes. Medical365 allows user-level language preferences — billing staff can work in Hindi while clinical staff work in English, all within the same Ajmer hospital system."),
            ("Does Medical365 support Hindi language prescriptions for patients in Ajmer?",
             "Yes. Doctors in Ajmer can generate prescriptions with Hindi medicine names and instructions, which patients can easily understand and follow."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "C-Scheme", "feature": "Healthcare Data Security and Compliance",
        "slug": "healthcare-data-security-compliance-c-scheme",
        "h1": "Healthcare Data Security & Compliance in C-Scheme, Jaipur — Secure by Design",
        "meta_title": "Healthcare Data Security & Compliance in C-Scheme Jaipur | Medical365",
        "meta_desc": "Enterprise healthcare data security for hospitals in C-Scheme, Jaipur. DPDP Act 2023, ABDM, ISO 27001 compliant with end-to-end encryption and audit trails.",
        "faq": [
            ("What data security standards does Medical365 comply with for C-Scheme hospitals?",
             "Medical365 complies with DPDP Act 2023, ABDM data standards, ISO 27001, and EHR Standards of India — providing C-Scheme hospitals with a comprehensive data security framework."),
            ("How does Medical365 protect patient data from breaches in C-Scheme?",
             "Medical365 uses AES-256 encryption, role-based access control, multi-factor authentication, IP whitelisting, and complete audit trails — ensuring patient data in C-Scheme is protected at every layer."),
            ("Does Medical365 conduct regular security audits for hospitals in C-Scheme?",
             "Yes. Medical365 undergoes annual third-party penetration testing, quarterly vulnerability assessments, and continuous security monitoring — with findings shared with hospital administrators."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Jodhpur", "feature": "Medical Robotic Process Automation",
        "slug": "medical-robotic-process-automation-jodhpur",
        "h1": "Medical Robotic Process Automation (RPA) in Jodhpur — Automate the Repetitive",
        "meta_title": "Medical Robotic Process Automation in Jodhpur | Medical365 RPA",
        "meta_desc": "Healthcare RPA solutions for hospitals in Jodhpur. Automate billing reconciliation, claim submissions, report generation, and appointment reminders with Medical365.",
        "faq": [
            ("What processes can be automated with Medical365 RPA for Jodhpur hospitals?",
             "Medical365 RPA automates insurance claim submissions, billing reconciliation, lab report dispatch, appointment reminder calls, monthly MIS report generation, and regulatory compliance filings for Jodhpur hospitals."),
            ("How much staff time does Medical365 RPA save for Jodhpur hospitals?",
             "Hospitals in Jodhpur typically save 200–500 hours of manual work per month after deploying Medical365 RPA — allowing staff to focus on patient care instead of paperwork."),
            ("Is RPA deployment disruptive for Jodhpur hospital operations?",
             "No. Medical365 RPA bots run in the background without affecting existing workflows. Deployment is phased, with each bot tested thoroughly before go-live."),
        ],
        "testimonial_idx": 2,
    },
    # ── Category 6: HR, Admin & Marketing ────────────────────────────────────
    {
        "location": "Jaipur", "feature": "Hospital HRMS",
        "slug": "hospital-hrms-jaipur",
        "h1": "Hospital HRMS in Jaipur — Manage Every Staff Member with Precision",
        "meta_title": "Hospital HRMS in Jaipur | Medical365 Human Resource Management",
        "meta_desc": "Complete hospital HRMS for healthcare facilities in Jaipur. Staff records, payroll, attendance, leave management, and credential tracking with Medical365.",
        "faq": [
            ("What HR features does Medical365 HRMS offer for hospitals in Jaipur?",
             "Medical365 HRMS covers employee records, biometric attendance integration, leave management, payroll with PF/ESI, credential and license expiry tracking, and performance appraisals for Jaipur hospital staff."),
            ("Can Medical365 HRMS handle payroll for doctors on retainer in Jaipur?",
             "Yes. Medical365 supports multiple pay structures — salaried, retainer, per-session, and revenue-sharing — covering all types of doctor engagements in Jaipur hospitals."),
            ("Does Medical365 HRMS track medical staff certifications and renewals in Jaipur?",
             "Yes. License expiry, CME credits, and credential renewal dates are tracked with automated alerts sent to HR before they fall due."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Udaipur", "feature": "Healthcare CRM Software",
        "slug": "healthcare-crm-software-udaipur",
        "h1": "Healthcare CRM Software in Udaipur — Build Lasting Patient Relationships",
        "meta_title": "Healthcare CRM Software in Udaipur | Medical365 Patient CRM",
        "meta_desc": "Medical365's healthcare CRM for hospitals in Udaipur. Track patient journeys, manage referrals, run health campaigns, and improve patient retention with ease.",
        "faq": [
            ("How does Medical365 CRM help hospitals in Udaipur retain patients?",
             "Medical365 CRM tracks patient visit history, preferences, and health milestones — enabling Udaipur hospitals to send personalised health reminders, anniversary wishes, and targeted wellness campaigns."),
            ("Can Medical365 CRM manage doctor referrals for Udaipur hospitals?",
             "Yes. Medical365 tracks referral sources, referring doctor performance, and referral revenue — helping Udaipur hospitals build and nurture strong referral networks."),
            ("Does Medical365 CRM integrate with social media marketing for Udaipur hospitals?",
             "Medical365 CRM integrates with WhatsApp and email for campaign execution. For social media, it exports audience segments compatible with digital marketing platforms."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Bapu Nagar", "feature": "Hospital Bed Management Software",
        "slug": "hospital-bed-management-software-bapu-nagar",
        "h1": "Hospital Bed Management Software in Bapu Nagar, Jaipur — Every Bed Optimised",
        "meta_title": "Hospital Bed Management Software in Bapu Nagar Jaipur | Medical365",
        "meta_desc": "Real-time bed management for hospitals in Bapu Nagar, Jaipur. Live bed availability, turnaround tracking, housekeeping integration, and occupancy analytics with Medical365.",
        "faq": [
            ("How does Medical365 bed management work for hospitals in Bapu Nagar?",
             "A real-time colour-coded bed map shows available, occupied, cleaning, and blocked beds across all wards. Admissions can be made in one click, and housekeeping is alerted automatically on discharge."),
            ("Can Medical365 predict bed availability for Bapu Nagar hospital planning?",
             "Yes. Medical365 uses discharge planning timelines and historical occupancy patterns to forecast bed availability, helping Bapu Nagar hospitals plan elective admissions optimally."),
            ("Does Medical365 bed management integrate with the ICU for Bapu Nagar hospitals?",
             "Yes. ICU beds, step-down wards, and general wards are all managed in one dashboard, with real-time monitoring of patient location and bed status across Bapu Nagar hospital."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Sikar", "feature": "Canteen Management Software",
        "slug": "canteen-management-software-hospitals-sikar",
        "h1": "Canteen Management Software for Hospitals in Sikar — Diet, Billing & Inventory Unified",
        "meta_title": "Canteen Management Software for Hospitals in Sikar | Medical365",
        "meta_desc": "Hospital canteen management for facilities in Sikar. Patient diet orders, staff meals, inventory tracking, GST billing, and nutritional compliance with Medical365.",
        "faq": [
            ("How does Medical365 canteen management work for hospitals in Sikar?",
             "Medical365 connects the clinical team's diet orders with the canteen kitchen, manages staff meal bookings, tracks food inventory, and generates GST-compliant canteen billing for Sikar hospitals."),
            ("Can Medical365 support patient-specific diet plans in Sikar hospital canteens?",
             "Yes. Dietitian-prescribed meal plans are sent directly to the kitchen, ensuring diabetic, low-sodium, or post-surgical diets are prepared correctly for each patient in Sikar."),
            ("Does Medical365 canteen module track food inventory and wastage in Sikar?",
             "Yes. Real-time ingredient inventory tracks usage, calculates wastage, and triggers reorder alerts — reducing food costs for Sikar hospital canteens."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Rajasthan", "feature": "Healthcare Digital Marketing Services",
        "slug": "healthcare-digital-marketing-services-rajasthan",
        "h1": "Healthcare Digital Marketing Services in Rajasthan — Grow Your Patient Base Online",
        "meta_title": "Healthcare Digital Marketing Services in Rajasthan | Medical365",
        "meta_desc": "Digital marketing for hospitals and clinics across Rajasthan. SEO, Google Ads, social media, and patient acquisition campaigns powered by Medical365's platform.",
        "faq": [
            ("What digital marketing services does Medical365 offer for hospitals in Rajasthan?",
             "Medical365 provides local SEO, Google Ads management, WhatsApp marketing, social media content, and patient review management — a complete digital growth solution for Rajasthan healthcare providers."),
            ("How does local SEO help hospitals get more patients in Rajasthan?",
             "Local SEO ensures your hospital appears at the top of Google searches for healthcare queries in your city. Medical365 creates location-specific pages — like this one — that drive qualified patient traffic from across Rajasthan."),
            ("Can Medical365 run Google Ads for speciality services in Rajasthan?",
             "Yes. Medical365 creates and manages targeted Google Search and Display campaigns for specific specialities — cardiology, orthopaedics, oncology — driving the right patients to your Rajasthan hospital."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Malviya Nagar", "feature": "Hospital Referral Management Software",
        "slug": "hospital-referral-management-software-malviya-nagar",
        "h1": "Hospital Referral Management Software in Malviya Nagar, Jaipur",
        "meta_title": "Hospital Referral Management Software in Malviya Nagar Jaipur | Medical365",
        "meta_desc": "Track and grow doctor referral networks for hospitals in Malviya Nagar, Jaipur. Referral dashboards, referring doctor portals, and commission tracking with Medical365.",
        "faq": [
            ("How does Medical365 help hospitals in Malviya Nagar track doctor referrals?",
             "Medical365 tracks every referred patient from source to admission, attributing revenue to the referring doctor. Malviya Nagar hospital management sees referral volume, value, and conversion rates in real time."),
            ("Can referring doctors in Malviya Nagar track their patients' status in Medical365?",
             "Yes. Medical365 provides a secure referring doctor portal where practitioners in Malviya Nagar can see real-time updates on their referred patients' consultations, admissions, and test results."),
            ("Does Medical365 automate referral commission calculations for Malviya Nagar hospitals?",
             "Yes. Medical365 calculates referral fees based on predefined agreements, generates monthly statements, and integrates with payroll for seamless commission payouts."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Jodhpur", "feature": "Medical Asset and Inventory Management",
        "slug": "medical-asset-inventory-management-jodhpur",
        "h1": "Medical Asset & Inventory Management in Jodhpur — Know Where Everything Is",
        "meta_title": "Medical Asset & Inventory Management in Jodhpur | Medical365",
        "meta_desc": "Complete medical asset and inventory management for hospitals in Jodhpur. Equipment tracking, maintenance schedules, consumables, and AMC management with Medical365.",
        "faq": [
            ("What assets can Medical365 track for hospitals in Jodhpur?",
             "Medical365 tracks medical equipment (ventilators, ECG machines, surgical instruments), furniture, IT assets, consumables, and implants — with location, condition, and maintenance history for every item in Jodhpur hospitals."),
            ("How does Medical365 manage equipment maintenance for Jodhpur hospitals?",
             "Preventive maintenance schedules and AMC (Annual Maintenance Contract) reminders are automated. Engineers are assigned digitally, and completion is confirmed with a mobile sign-off."),
            ("Can Medical365 generate equipment utilisation reports for Jodhpur hospital CFOs?",
             "Yes. Utilisation dashboards show which high-value equipment in Jodhpur is fully utilised and which needs redeployment — helping optimise capital expenditure decisions."),
        ],
        "testimonial_idx": 4,
    },
    # ── Category 7: Government & Large Scale ──────────────────────────────────
    {
        "location": "Rajasthan", "feature": "Integrated Population Healthcare Management",
        "slug": "integrated-population-healthcare-management-rajasthan",
        "h1": "Integrated Population Healthcare Management in Rajasthan — State-Scale Health Intelligence",
        "meta_title": "Integrated Population Healthcare Management in Rajasthan | Medical365",
        "meta_desc": "Scalable population health management for Rajasthan government and NGOs. Disease surveillance, NHM program tracking, ABHA integration, and health analytics.",
        "faq": [
            ("What is integrated population healthcare management and who needs it in Rajasthan?",
             "It is a system that tracks health outcomes across large populations — ideal for Rajasthan state government, district health authorities, and large NGOs managing community health programs."),
            ("Can Medical365 support NHM programs across Rajasthan?",
             "Yes. Medical365 supports National Health Mission (NHM) program workflows including RMNCH+A, TB, malaria, and non-communicable disease monitoring with standardised reporting for Rajasthan."),
            ("How does Medical365 handle data from hundreds of PHCs and CHCs in Rajasthan?",
             "Medical365's multi-facility architecture aggregates data from all connected PHCs, CHCs, and district hospitals in Rajasthan into a single analytics dashboard for state health administrators."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Jaipur", "feature": "Multi-Facility Hospital Software",
        "slug": "multi-facility-hospital-software-jaipur",
        "h1": "Multi-Facility Hospital Software in Jaipur — One System for All Your Branches",
        "meta_title": "Multi-Facility Hospital Software in Jaipur | Medical365 Group HMS",
        "meta_desc": "Medical365 multi-facility HMS for hospital groups in Jaipur. Centralised patient records, inter-branch referrals, consolidated billing, and group-level analytics.",
        "faq": [
            ("How does Medical365 support multi-facility hospital groups in Jaipur?",
             "Medical365 provides a centralised dashboard where Jaipur hospital group administrators see all branches' performance in real time, with shared patient records, inter-branch referrals, and consolidated group billing."),
            ("Can patients in Jaipur transfer between hospital branches seamlessly on Medical365?",
             "Yes. Patient records are instantly accessible at any branch of the hospital group in Jaipur, enabling seamless inter-facility transfers without re-registration or record duplication."),
            ("Does Medical365 support separate billing entities for different branches in Jaipur?",
             "Yes. Each branch maintains its own billing entity, GST registration, and P&L — while group-level reports aggregate all branches for Jaipur hospital group management."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Jodhpur", "feature": "Public Health Surveillance Software",
        "slug": "public-health-surveillance-software-jodhpur",
        "h1": "Public Health Surveillance Software in Jodhpur — Early Warning, Faster Response",
        "meta_title": "Public Health Surveillance Software in Jodhpur | Medical365",
        "meta_desc": "Disease surveillance and public health monitoring for Jodhpur. Track disease outbreaks, notifiable conditions, and population health trends in real time with Medical365.",
        "faq": [
            ("How does Medical365 help public health surveillance in Jodhpur?",
             "Medical365 aggregates disease data from connected hospitals and clinics in Jodhpur, generating real-time outbreak alerts and trend dashboards for district health officers."),
            ("Which notifiable diseases does Medical365 track for Jodhpur public health?",
             "Medical365 tracks all IDSP (Integrated Disease Surveillance Programme) notifiable diseases including dengue, malaria, typhoid, TB, and seasonal illness clusters across Jodhpur."),
            ("Can Medical365 generate IDSP weekly reports for Jodhpur district health authorities?",
             "Yes. Medical365 auto-generates P, L, and S-form IDSP reports and submits them to state health portals, saving Jodhpur health officers hours of manual reporting."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Kota", "feature": "ABHA Compliance Software",
        "slug": "abha-compliance-software-hospitals-kota",
        "h1": "ABHA Compliance Software for Hospitals in Kota — Linked, Verified & Ready",
        "meta_title": "ABHA Compliance Software for Hospitals in Kota | Medical365",
        "meta_desc": "Medical365 ABHA compliance for hospitals in Kota. Create ABHA IDs, link health records, and connect to the national ABDM health information exchange seamlessly.",
        "faq": [
            ("What is ABHA and why do hospitals in Kota need to be compliant?",
             "ABHA (Ayushman Bharat Health Account) is India's unique health ID. Hospitals in Kota that are ABHA-compliant can link patient records to the national health information exchange, improving continuity of care and qualifying for government health schemes."),
            ("How does Medical365 help Kota hospitals create ABHA IDs for patients?",
             "At registration, Medical365 verifies the patient's Aadhaar or mobile number and creates an ABHA ID in under 30 seconds — no additional app or portal needed for Kota hospital staff."),
            ("Does Medical365 ABHA compliance affect existing workflows for Kota hospitals?",
             "No. ABHA ID creation is seamlessly embedded in the existing patient registration flow. Staff in Kota hospitals require no additional steps or training."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Ajmer", "feature": "Pradhan Mantri Yojana Support Software",
        "slug": "pradhan-mantri-yojana-support-software-ajmer",
        "h1": "Pradhan Mantri Yojana Support Software for Hospitals in Ajmer",
        "meta_title": "Pradhan Mantri Yojana Support Software in Ajmer | Medical365 PMJAY",
        "meta_desc": "Complete PMJAY and Chiranjeevi Yojana support for hospitals in Ajmer. Eligibility verification, pre-authorization, claim submission, and reconciliation with Medical365.",
        "faq": [
            ("How does Medical365 support PMJAY claims for Ajmer hospitals?",
             "Medical365 verifies patient eligibility via Aadhaar, manages pre-authorization requests, submits claims to the PMJAY portal, and tracks reimbursement status — all within the HMS for Ajmer hospitals."),
            ("Does Medical365 support Chiranjeevi Yojana for Rajasthan hospitals in Ajmer?",
             "Yes. Medical365 is fully configured for Chiranjeevi Yojana claim workflows, package rates, and reporting requirements specific to Rajasthan, including Ajmer district hospitals."),
            ("How quickly are government scheme claims processed through Medical365 in Ajmer?",
             "Medical365 reduces claim processing time from days to hours. Automated checks for missing documents and incorrect codes prevent rejections before submission for Ajmer hospitals."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Bharatpur", "feature": "Vaccine Management System",
        "slug": "vaccine-management-system-bharatpur",
        "h1": "Vaccine Management System in Bharatpur — Track Every Dose, Every Child",
        "meta_title": "Vaccine Management System in Bharatpur | Medical365",
        "meta_desc": "Comprehensive vaccine management for hospitals and PHCs in Bharatpur. Cold chain tracking, immunisation schedules, beneficiary tracking, and government reporting.",
        "faq": [
            ("What does Medical365 vaccine management system do for facilities in Bharatpur?",
             "Medical365 tracks vaccine inventory across cold chain points, manages immunisation schedules for children and adults, records beneficiary data, and generates district immunisation reports for Bharatpur health authorities."),
            ("How does Medical365 ensure cold chain compliance for vaccines in Bharatpur?",
             "Medical365 integrates with digital temperature monitoring devices and sends automated alerts when cold chain temperatures breach thresholds at any Bharatpur storage point."),
            ("Can Medical365 track defaulter children who missed vaccines in Bharatpur?",
             "Yes. Medical365 identifies defaulters automatically and triggers outreach to the field health worker (ASHA, ANM) via SMS, ensuring no child in Bharatpur misses their due immunisation."),
        ],
        "testimonial_idx": 0,
    },
    # ── Additional Jaipur local area pages ────────────────────────────────────
    {
        "location": "Raja Park", "feature": "EMR Software",
        "slug": "emr-software-raja-park-jaipur",
        "h1": "EMR Software for Clinics in Raja Park, Jaipur — Go Paperless in 7 Days",
        "meta_title": "EMR Software for Clinics in Raja Park Jaipur | Medical365",
        "meta_desc": "Top-rated EMR software for clinics and hospitals in Raja Park, Jaipur. Digital records, e-prescriptions, ABDM compliance, and offline sync with Medical365.",
        "faq": [
            ("How does Medical365 EMR help clinics in Raja Park go paperless?",
             "Medical365 replaces paper prescriptions, case sheets, and lab registers with digital workflows. Raja Park clinics are typically fully paperless within 7 days of go-live."),
            ("Does Medical365 EMR support specialist templates for Raja Park clinics?",
             "Yes. Medical365 offers 50+ specialty-specific EMR templates for general medicine, dermatology, gynaecology, paediatrics, and more — customisable for any Raja Park clinic."),
            ("Can multiple doctors in a Raja Park clinic use Medical365 EMR simultaneously?",
             "Yes. Medical365 is a cloud-based multi-user system. Any number of doctors and staff can use it concurrently from any device in Raja Park."),
        ],
        "testimonial_idx": 1,
    },
    {
        "location": "Vaishali Nagar", "feature": "Clinic Management System",
        "slug": "clinic-management-system-vaishali-nagar",
        "h1": "Clinic Management System in Vaishali Nagar, Jaipur — Complete, Cloud & Affordable",
        "meta_title": "Clinic Management System in Vaishali Nagar Jaipur | Medical365",
        "meta_desc": "All-in-one clinic management system for clinics in Vaishali Nagar, Jaipur. Appointments, EMR, billing, pharmacy, and patient app in one affordable platform.",
        "faq": [
            ("What does Medical365 offer for multi-specialty clinics in Vaishali Nagar?",
             "Medical365 covers OPD scheduling, EMR, billing, pharmacy, lab integration, telemedicine, and patient communication — all in one platform for Vaishali Nagar clinics of any size."),
            ("Is Medical365 affordable for small clinics in Vaishali Nagar?",
             "Yes. Medical365 offers flexible monthly subscriptions starting from solo practitioners, with no large upfront costs. Contact us for a Vaishali Nagar clinic-specific pricing quote."),
            ("Can I try Medical365 before committing for my Vaishali Nagar clinic?",
             "Yes. Book a free 30-day trial with full features — no credit card required. Our team provides free onboarding support for your Vaishali Nagar clinic."),
        ],
        "testimonial_idx": 2,
    },
    {
        "location": "Tonk Road", "feature": "Hospital Management Software",
        "slug": "hospital-management-software-tonk-road",
        "h1": "Hospital Management Software in Tonk Road, Jaipur — Built for Busy Hospitals",
        "meta_title": "Hospital Management Software in Tonk Road Jaipur | Medical365 HMS",
        "meta_desc": "Complete hospital management software for facilities on Tonk Road, Jaipur. OPD, IPD, EMR, billing, pharmacy, lab, and analytics in one cloud platform.",
        "faq": [
            ("What makes Medical365 the right HMS for hospitals on Tonk Road?",
             "Medical365 is built for the pace of busy Jaipur hospitals — with fast OPD workflows, real-time bed management, and automated billing that eliminates queues at the billing counter."),
            ("Can Medical365 be customised for the specialities at our Tonk Road hospital?",
             "Yes. Medical365 is fully configurable. Speciality templates, workflow sequences, and department structures are customised during onboarding for your Tonk Road hospital."),
            ("Does Medical365 offer on-site training for Tonk Road hospital staff?",
             "Yes. Our Jaipur-based implementation team provides on-site training at your Tonk Road facility, with ongoing support available via phone, chat, and remote access."),
        ],
        "testimonial_idx": 3,
    },
    {
        "location": "Jhotwara", "feature": "Telemedicine Platform",
        "slug": "telemedicine-platform-jhotwara-jaipur",
        "h1": "Telemedicine Platform for Clinics in Jhotwara, Jaipur — Virtual Care, Real Results",
        "meta_title": "Telemedicine Platform for Clinics in Jhotwara Jaipur | Medical365",
        "meta_desc": "Launch telemedicine at your Jhotwara clinic with Medical365. HD video consults, e-prescriptions, online payments, and ABDM-compliant digital records.",
        "faq": [
            ("How can my Jhotwara clinic start telemedicine with Medical365?",
             "Simply subscribe to Medical365, share your branded video consultation link with patients, and start seeing them online. Setup takes under 48 hours for Jhotwara clinics."),
            ("What equipment do I need for telemedicine at my Jhotwara clinic?",
             "Just a laptop or smartphone with a camera and a stable internet connection. Medical365 telemedicine works in any browser — no separate app installation for doctors."),
            ("Can patients in Jhotwara pay for telemedicine consultations before joining?",
             "Yes. Medical365 collects consultation fees via UPI or card before the video call begins — eliminating payment friction for Jhotwara patients."),
        ],
        "testimonial_idx": 4,
    },
    {
        "location": "Pali", "feature": "Hospital Management Software",
        "slug": "hospital-management-software-pali",
        "h1": "Hospital Management Software in Pali, Rajasthan — Modern HMS for a Growing City",
        "meta_title": "Hospital Management Software in Pali Rajasthan | Medical365",
        "meta_desc": "Trusted hospital management software for clinics and hospitals in Pali, Rajasthan. OPD, IPD, EMR, billing, and pharmacy on one cloud platform — Book a free demo.",
        "faq": [
            ("What hospital management features does Medical365 offer for Pali facilities?",
             "Medical365 covers OPD and IPD management, EMR, pharmacy, lab, billing, telemedicine, and patient communication — a complete HMS for hospitals and clinics in Pali."),
            ("Does Medical365 provide on-site support in Pali, Rajasthan?",
             "Yes. Our Rajasthan implementation team visits Pali for on-site setup, data migration, and staff training — ensuring a smooth go-live for your facility."),
            ("Is Medical365 suitable for small nursing homes in Pali?",
             "Absolutely. Medical365 scales from a 5-bed nursing home to a 500-bed hospital. Small nursing homes in Pali get the same powerful features at a cost-effective price."),
        ],
        "testimonial_idx": 0,
    },
    {
        "location": "Sri Ganganagar", "feature": "Clinic Management System",
        "slug": "clinic-management-system-sri-ganganagar",
        "h1": "Clinic Management System in Sri Ganganagar — Efficient, Affordable, Cloud-Based",
        "meta_title": "Clinic Management System in Sri Ganganagar | Medical365",
        "meta_desc": "Medical365 clinic management system for Sri Ganganagar. Digital appointments, EMR, automated billing, and pharmacy management for clinics of all sizes.",
        "faq": [
            ("What makes Medical365 the right choice for clinics in Sri Ganganagar?",
             "Medical365 offers offline functionality for low-connectivity periods, Hindi language support, and affordable pricing — making it ideal for clinics in Sri Ganganagar and the surrounding region."),
            ("Can Medical365 support clinics seeing 100+ patients a day in Sri Ganganagar?",
             "Yes. Medical365 is built for high-volume environments. Sri Ganganagar clinics with 100–300 daily patients use Medical365 for smooth, error-free operations."),
            ("Is there local support available for Medical365 in Sri Ganganagar?",
             "Yes. Medical365 provides remote support via phone, chat, and video — plus periodic on-site visits for Sri Ganganagar customers. Our support team is available 6 days a week."),
        ],
        "testimonial_idx": 1,
    },
]


def slugify(text):
    return re.sub(r'[^a-z0-9-]', '', re.sub(r'\s+', '-', text.lower()))


def render_page(page_data, template, testimonials):
    t = testimonials[page_data["testimonial_idx"] % len(testimonials)]
    location = page_data["location"]
    feature = page_data["feature"]

    faqs = page_data["faq"]
    faq1_q, faq1_a = faqs[0]
    faq2_q, faq2_a = faqs[1]
    faq3_q, faq3_a = faqs[2]

    postal = POSTAL_CODES.get(location, "302001")
    location_slug = slugify(location)

    replacements = {
        "{{meta_title}}": page_data["meta_title"],
        "{{meta_description}}": page_data["meta_desc"],
        "{{slug}}": page_data["slug"],
        "{{location}}": location,
        "{{location_slug}}": location_slug,
        "{{feature}}": feature,
        "{{h1_heading}}": page_data["h1"],
        "{{postal_code}}": postal,
        "{{faq1_question}}": faq1_q,
        "{{faq1_answer}}": faq1_a,
        "{{faq2_question}}": faq2_q,
        "{{faq2_answer}}": faq2_a,
        "{{faq3_question}}": faq3_q,
        "{{faq3_answer}}": faq3_a,
        "{{testimonial_quote}}": t["quote"],
        "{{testimonial_name}}": t["name"],
        "{{testimonial_role}}": t["role"],
        "{{testimonial_avatar_initials}}": t["initials"],
    }

    html = template
    for k, v in replacements.items():
        html = html.replace(k, v)
    return html


def main():
    total = 0
    for page in PAGES:
        html = render_page(page, TEMPLATE, TESTIMONIALS)
        filename = page["slug"] + ".html"
        outpath = os.path.join(OUTPUT_DIR, filename)
        with open(outpath, "w", encoding="utf-8") as f:
            f.write(html)
        total += 1
        print(f"  ✓  {filename}")

    print(f"\n✅  Generated {total} pages → {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
