export const products = [
  { slug: 'abha-compliance-software', name: 'ABHA Compliance Software' },
  { slug: 'clinic-management-system', name: 'Clinic Management System' },
  { slug: 'clinical-assessment-form-software', name: 'Clinical Assessment Forms' },
  { slug: 'emr-software', name: 'EMR Software' },
  { slug: 'fhir-hl7-compliant-software', name: 'FHIR HL7 Compliant Software' },
  { slug: 'healthcare-crm', name: 'Healthcare CRM' },
  { slug: 'healthcare-feedback-satisfaction-surveys', name: 'Patient Feedback Surveys' },
  { slug: 'healthcare-kiosk-providers', name: 'Healthcare Kiosk' },
  { slug: 'hospital-bed-management-software', name: 'Bed Management Software' },
  { slug: 'hospital-data-backup-recovery', name: 'Hospital Data Backup' },
  { slug: 'hospital-hrms', name: 'Hospital HRMS' },
  { slug: 'hospital-it-cloud-migration', name: 'Hospital Cloud Migration' },
  { slug: 'hospital-management-software', name: 'Hospital Management Software' },
  { slug: 'hospital-online-scheduling-software', name: 'Online Scheduling Software' },
  { slug: 'hospital-queue-token-management', name: 'Queue Management Software' },
  { slug: 'inpatient-management-software', name: 'Inpatient (IPD) Software' },
  { slug: 'integrated-population-healthcare-management', name: 'Population Health Management' },
  { slug: 'lims-laboratory-information-management', name: 'Laboratory (LIMS) Software' },
  { slug: 'medical-asset-inventory-management', name: 'Asset & Inventory Management' },
  { slug: 'medical-camp-management-software', name: 'Medical Camp Management' },
  { slug: 'medical-robotic-process-automation', name: 'Medical RPA' },
  { slug: 'multi-facility-hospital-software', name: 'Multi-Facility Hospital Software' },
  { slug: 'nursing-management-system', name: 'Nursing Management System' },
  { slug: 'operation-theater-management', name: 'Operation Theater Management' },
  { slug: 'outpatient-software-solutions', name: 'Outpatient (OPD) Software' },
  { slug: 'patient-portal-software', name: 'Patient Portal Software' },
  { slug: 'revenue-cycle-management', name: 'Revenue Cycle Management' },
  { slug: 'telemedicine-platform', name: 'Telemedicine Platform' },
  { slug: 'vaccine-management-system', name: 'Vaccine Management System' },
  { slug: 'virtual-opd-software', name: 'Virtual OPD Software' }
];

export const locations = [
  { slug: 'jaipur', name: 'Jaipur' },
  { slug: 'ajmer', name: 'Ajmer' },
  { slug: 'alwar', name: 'Alwar' },
  { slug: 'kota', name: 'Kota' },
  { slug: 'jodhpur', name: 'Jodhpur' },
  { slug: 'bikaner', name: 'Bikaner' },
  { slug: 'udaipur', name: 'Udaipur' },
  { slug: 'sikar', name: 'Sikar' },
  { slug: 'pali', name: 'Pali' },
  { slug: 'bharatpur', name: 'Bharatpur' },
  { slug: 'bhilwara', name: 'Bhilwara' },
  { slug: 'sri-ganganagar', name: 'Sri Ganganagar' },
  { slug: 'bapu-nagar-jaipur', name: 'Bapu Nagar, Jaipur' },
  { slug: 'c-scheme-jaipur', name: 'C-Scheme, Jaipur' },
  { slug: 'jagatpura-jaipur', name: 'Jagatpura, Jaipur' },
  { slug: 'jhotwara-jaipur', name: 'Jhotwara, Jaipur' },
  { slug: 'malviya-nagar-jaipur', name: 'Malviya Nagar, Jaipur' },
  { slug: 'mansarovar-jaipur', name: 'Mansarovar, Jaipur' },
  { slug: 'raja-park-jaipur', name: 'Raja Park, Jaipur' },
  { slug: 'tonk-road-jaipur', name: 'Tonk Road, Jaipur' },
  { slug: 'vaishali-nagar-jaipur', name: 'Vaishali Nagar, Jaipur' },
  { slug: 'vidyadhar-nagar-jaipur', name: 'Vidyadhar Nagar, Jaipur' }
];
